### ISSUE TITLE
「3 arguments are required, 2 given」エラーについて

### ISSUE THREAD

**Issue by usr7072** [joomlajp/Joomla-in-Japanese#17]
「3 arguments are required, 2 given」エラーが発生することを確認しています。

当方で確認しているのはUpdate関連のページとなりまして、関連する「com_installer.ini」ファイルの修正にて回避が可能であることを確認しました。
「%s」が複数記述されている事が原因で、「3 arguments are required, 2 given」エラーが発生している模様です。

（該当箇所の一部）
COM_INSTALLER_MSG_WARNINGS_PHPUPLOADNOTWRITEABLEDESC="このフォルダは書き込み可能ではありません。エクステンションをアップロードする際に問題が発生する可能性があります。エクステンションのアップロードで問題がある場合、configuration.php で定義されているディレクトリが存在するかを確認する、あるいは「%s」をチェックし、書き込み可能に設定し、こ>れでその問題が修正されたかをご確認ください。「%s」をチェックし、書き込み可能に設定し、これでその問題が修正されたかをご確認ください。"

（修正後）
COM_INSTALLER_MSG_WARNINGS_PHPUPLOADNOTWRITEABLEDESC="「%s」は書き込み可能ではありません。エクステンションをアップロードする際に問題が発生する可能性があります。エクステンションのアップロードで問題がある場合、configuration.php で定義されているディレクトリが存在するかを確認し、書き込み可能に設定し、これでその問題が修正されたかをご確認ください。"

 参考ページ・当方環境につきましても記載致しますので、お手すきの際にご確認お願い致します。
参考：https://issues.joomla.org/tracker/joomla-cms/35002

PHP Built ｜On Linux [vm-web](http://vm-web/) 6.4.13-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 30 17:07:31 UTC 2023 x86_64
PHPのバージョン｜8.2.10
ウェブサーバ｜Apache/2.4.57 (Fedora Linux) OpenSSL/3.0.9
WebサーバーからPHPへのインターフェース｜fpm-fcgi
Joomla!のバージョン｜Joomla! 4.3.4 Stable [ Bora ] 22-August-2023 16:00 GMT

**Comment by Richell** [comment]
4.4.0 にて反映させていただきました。ありがとうございました。
